name: Build HTML and PDF

on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y $(cat apt-packages.txt)
        pip3 install setuptools
        pip3 install -r requirements.txt
        
    - name: Build GitHub Pages
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
        git config --global user.email "cvbot@jorgebg.com"
        git config --global user.name "CV Bot"

        python3 -m cv pdf
        mkdir -p .data
        cp build/tex/cv.pdf ".data/Jorge Barata.pdf"
        cp cv.md .data/index.md
        cp cv.ext.md .data/extended.md
        git stash
        git checkout gh-pages
        mv .data/* .
        git add "Jorge Barata.pdf" index.md extended.md
        git commit -m"Automated update"
        rmdir .data
        git push origin gh-pages:gh-pages
